
services:

  go-mongodb:
    container_name: go-mongodb
    image: mongo:4.4.14-rc0
    profiles:
      - "db"
    volumes:
      - medusa-data:/data/db
    networks:
      - medusa-network
    ports:
      - "27017:27017"  
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    command: mongod --logpath=/dev/null   
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  medusa-data:     

networks:
  medusa-network: